# This is a manifest file that'll be compiled into application.js, which will include all the files
# listed below.
#
#= require jquery
#= require jquery_ujs
#= require alertify
#=  require_self

window.onPinchStart = (e)->
  console.log "pinch", e.type
$ ->
  # PREVENT BROWSER BUMP
  # LOCK TO PORTRAIT MODE
 

  $(window).on 'scroll', (e) ->
    scrollAmount = $(this).scrollTop()
    if scrollAmount < 1
      $(this).scrollTop 1
    if scrollAmount > $(document).height() - $(window).height()
      $(this).scrollTop $(window).height()
    return
  return

window.GET = ->
  prmstr = window.location.search.substr(1)
  if prmstr != null and prmstr != '' then transformToAssocArray(prmstr) else {}

transformToAssocArray = (prmstr) ->
  params = {}
  prmarr = prmstr.split('&')
  i = 0
  while i < prmarr.length
    tmparr = prmarr[i].split('=')
    params[tmparr[0]] = tmparr[1]
    i++
  params

DOM = ->

FancyPrint = ->

# var params = getSearchParameters();

poly = (a, b, c, x) ->
  x ** 2 * a + x * b + c

norm = (arr) ->
  min = _.min(arr)
  max = _.max(arr)
  range = max - min
  _(arr).map (el) ->
    (el - min) / range

$ ->
  # PREVENT BROWSER BUMP
  $(window).on 'scroll', (e) ->
    scrollAmount = $(this).scrollTop()
    if scrollAmount < 1
      $(this).scrollTop 1
    if scrollAmount > $(document).height() - $(window).height()
      $(this).scrollTop $(window).height()
    return
  return
if !Date.now

  Date.now = ->
    (new Date).getTime()

DOM.tag = (tag, single) ->
  if single
    $ '<' + tag + '/>'
  else if typeof single == 'undefined'
    $ '<' + tag + '>' + '</' + tag + '>'
  else
    $ '<' + tag + '>' + '</' + tag + '>'

Object.size = (obj) ->
  size = 0
  key = undefined
  for key of obj
    `key = key`
    if obj.hasOwnProperty(key)
      size++
  size

FancyPrint.range = (prefix, arr) ->
  min = _.min(arr)
  max = _.max(arr)
  console.log prefix, ': [', min.toFixed(2), ', ', max.toFixed(2), '] -->', (max - min).toFixed(2)
  return

# ---
# generated by js2coffee 2.2.0